version: '3'

services:
  # サービス名を指定
  bff:
    # コンテナ名を指定
    container_name: bff
    # dockerfileとpathの指定
    build:
      dockerfile: ./docker/bff/dockerfile
      context: .
    tty: true
    volumes:
      - type: bind
        source: ./bff
        target: /bff
    # ホストマシンのポート8080を、docker内のポート8080にマッピングする
    ports:
      - "8080:8080"
    # ビルトインサーバーの起動
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080