version: '3'
services:
  bff:
    container_name: bff
    build:
      context: .
      dockerfile: ./docker/bff/dockerfile
    tty: true
    volumes:
      - ./bff:/app
    ports:
      - "9000:9000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9000
  pdf-parser:
    container_name: pdf-parser
    build:
      context: .
      dockerfile: ./timetable-parser/docker/Dockerfile
    tty: true
    volumes:
      - ./timetable-parser:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000