FROM python:3.11.2-buster
WORKDIR /app
COPY ./docker/bff/requirements.txt .
RUN /usr/local/bin/python -m pip install --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir uvicorn