# ベースイメージ
FROM ubuntu:20.04

# javaのインストール
RUN apt-get update \
&& apt-get upgrade -y \
&& apt-get install -y --no-install-recommends bash \
&& apt-get install -y --no-install-recommends unzip \
&& apt-get install -y --no-install-recommends curl \
&& apt-get install -y --no-install-recommends openjdk-8-jre
# Pythonのインストール
RUN apt-get update && apt-get install -y python3.8 python3-pip

# 各種各引用コマンドインストール
RUN apt-get install -y curl iputils-ping procps vim tree

# ワーキングディレクトリの設定
WORKDIR /bff

# 設定ファイルのインストール
COPY docker/bff/requirements.txt /bff/
RUN python3.8 -m pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir uvicorn

#Javaの環境変数設定
ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"